name: ds-handbook
channels:
  - conda-forge
  - defaults
dependencies:
  # Python
  - python=3.11
  - pip
  
  # Core scientific computing
  - numpy>=1.24.0
  - pandas>=2.0.0
  - scipy>=1.10.0
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
  
  # Machine learning
  - scikit-learn>=1.3.0
  - xgboost>=1.7.0
  - lightgbm>=3.3.0
  
  # Deep learning
  - pytorch>=2.0.0
  - torchvision
  - torchaudio
  
  # Jupyter environment
  - jupyterlab>=4.0.0
  - notebook
  - ipywidgets>=8.0.0
  - jupyterlab-git>=0.41.0
  
  # Data processing
  - dask>=2023.6.0
  - pyspark>=3.4.0
  
  # Visualization
  - plotly>=5.15.0
  - bokeh>=3.2.0
  - altair>=5.0.0
  
  # Database
  - sqlalchemy>=2.0.0
  - psycopg2>=2.9.0
  
  # Development tools
  - pytest>=7.4.0
  - black>=23.7.0
  - flake8>=6.0.0
  - mypy>=1.5.0
  
  # Utilities
  - pyyaml>=6.0
  - tqdm>=4.65.0
  - requests>=2.31.0
  
  # R packages
  - r-base>=4.3.0
  - r-tidyverse
  - r-ggplot2
  - r-dplyr
  - r-shiny
  - r-plotly
  - r-caret
  - r-randomforest
  - r-xgboost
  - r-keras
  - r-reticulate
  
  # System dependencies
  - git
  - curl
  - wget
  - vim
  - htop
  
  # Additional packages via pip
  - pip:
    - mlflow>=2.5.0
    - streamlit>=1.25.0
    - transformers>=4.30.0
    - datasets>=2.12.0
    - opencv-python>=4.8.0
    - fastapi>=0.100.0
    - uvicorn>=0.23.0
    - pydantic>=2.0.0
    - wandb>=0.15.0
    - optuna>=3.2.0
    - boto3>=1.28.0
    - azure-storage-blob>=12.17.0
    - google-cloud-storage>=2.10.0
    - selenium>=4.10.0
    - beautifulsoup4>=4.12.0
    - scrapy>=2.9.0
    - pre-commit>=3.3.0
    - bandit>=1.7.0
    - safety>=2.3.0
