name: ds-handbook
channels:
  - conda-forge
  - defaults
dependencies:
  # Python
  - python=3.11
  - pip
  
  # Core data science
  - pandas>=2.0.0
  - numpy>=1.24.0
  - scipy>=1.10.0
  - scikit-learn>=1.3.0
  
  # Visualization
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
  - plotly>=5.15.0
  - bokeh>=3.0.0
  
  # Deep learning
  - tensorflow>=2.13.0
  - pytorch>=2.0.0
  - torchvision>=0.15.0
  
  # Database
  - sqlalchemy>=2.0.0
  - psycopg2>=2.9.0
  
  # Development
  - jupyterlab>=4.0.0
  - pytest>=7.4.0
  - black>=23.0.0
  - flake8>=6.0.0
  - mypy>=1.4.0
  
  # R
  - r-base>=4.3.0
  - r-tidyverse
  - r-caret
  - r-randomforest
  - r-xgboost
  - r-shiny
  
  # System
  - git
  - curl
  - wget
  
  # Pip packages
  - pip:
    - transformers>=4.30.0
    - mlflow>=2.5.0
    - optuna>=3.2.0
    - databricks-cli>=0.17.0
    - cryptography>=41.0.0
    - pyjwt>=2.8.0
    - fastapi>=0.100.0
    - uvicorn>=0.22.0
    - dask>=2023.6.0
    - polars>=0.18.0
    - boto3>=1.28.0
    - azure-storage-blob>=12.17.0
    - google-cloud-storage>=2.10.0
    - python-dotenv>=1.0.0
    - rich>=13.4.0
    - typer>=0.9.0
