# Workflow Integration Configuration
# ==================================

integration:
  auto_create_branches: true
  auto_assign_reviewers: true
  auto_send_notifications: true
  parallel_processing: true
  max_concurrent_workflows: 20
  workflow_timeout_hours: 72

# Stage Progression Mapping
workflow_mapping:
  draft_to_technical:
    source_stage: "draft"
    target_stage: "technical_review"
    branch_type: "technical_review"
    required_roles: ["technical_reviewer"]
    notifications: ["assignment_created"]
    conditions:
      - type: "content_validation"
        threshold: 70.0
      - type: "structure_check"
        required: true

  technical_to_educational:
    source_stage: "technical_review"
    target_stage: "educational_review"
    branch_type: "educational_review"
    required_roles: ["educational_reviewer"]
    notifications: ["review_submitted", "assignment_created"]
    conditions:
      - type: "technical_score"
        threshold: 80.0
      - type: "approval_required"
        count: 1

  educational_to_bias:
    source_stage: "educational_review"
    target_stage: "bias_assessment"
    branch_type: "bias_assessment"
    required_roles: ["bias_assessor"]
    notifications: ["review_submitted", "assignment_created"]
    conditions:
      - type: "educational_score"
        threshold: 75.0
      - type: "learning_objectives_met"
        required: true

  bias_to_security:
    source_stage: "bias_assessment"
    target_stage: "security_review"
    branch_type: "security_review"
    required_roles: ["security_reviewer"]
    notifications: ["review_submitted", "assignment_created"]
    conditions:
      - type: "bias_score"
        threshold: 70.0
      - type: "inclusivity_check"
        required: true

  security_to_final:
    source_stage: "security_review"
    target_stage: "final_approval"
    branch_type: "final_approval"
    required_roles: ["content_approver"]
    notifications: ["review_submitted", "assignment_created"]
    conditions:
      - type: "security_compliance"
        threshold: 85.0
      - type: "vulnerability_scan"
        required: true

  final_to_published:
    source_stage: "final_approval"
    target_stage: "published" 
    branch_type: "main"
    required_roles: ["publisher"]
    notifications: ["workflow_completed"]
    conditions:
      - type: "overall_score"
        threshold: 80.0
      - type: "all_quality_gates_passed"
        required: true

notifications:
  auto_start_scheduler: true
  reminder_intervals_hours: [24, 6, 1]
  escalation_threshold_hours: 48
  batch_notifications: true
  notification_cooldown_minutes: 15

quality_gates:
  enforce_quality_gates: true
  minimum_overall_score: 80.0
  auto_merge_threshold: 95.0
  bypass_on_emergency: false
  quality_gate_timeout_hours: 2

migration:
  auto_migrate_templates: true
  backup_before_migration: true
  validate_after_migration: true
  migration_batch_size: 50
  migration_cooldown_hours: 6

# Component Integration Settings
components:
  cms:
    enabled: true
    sync_metadata: true
    update_content_status: true
    track_file_changes: true

  workflow_orchestrator:
    enabled: true
    auto_create_workflows: true
    parallel_assignments: false
    deadline_buffer_hours: 4

  branching_strategy:
    enabled: true
    auto_cleanup_branches: true
    merge_strategy: "squash"
    create_backup_branches: false

  notification_system:
    enabled: true
    real_time_notifications: true
    digest_notifications: true
    notification_history_retention_days: 365

  migrator:
    enabled: true
    auto_migrations: false
    pre_migration_backup: true
    post_migration_validation: true

# Automation Rules
automation:
  auto_advance_on_approval:
    enabled: true
    conditions:
      - type: "score_threshold"
        value: 90.0
      - type: "no_blocking_issues"
        required: true
    exclude_stages: ["final_approval"]

  auto_escalate_overdue:
    enabled: true
    conditions:
      - type: "overdue_hours"
        value: 48
      - type: "no_reviewer_response"
        hours: 24
    actions:
      - "reassign_reviewer"
      - "notify_manager"
      - "extend_deadline"

  auto_reject_low_quality:
    enabled: false  # Disabled by default for safety
    conditions:
      - type: "quality_score"
        below: 50.0
      - type: "validation_errors"
        above: 10
    actions:
      - "reject_with_feedback"
      - "notify_author"

  auto_approve_high_quality:
    enabled: true
    conditions:
      - type: "quality_score"
        above: 95.0
      - type: "author_reputation"
        threshold: "high"
      - type: "content_complexity"
        level: "low"
    exclude_stages: ["security_review", "final_approval"]

# Performance Optimization
performance:
  cache_workflow_states: true
  cache_ttl_minutes: 30
  batch_database_operations: true
  async_notification_processing: true
  lazy_load_content: true
  optimize_git_operations: true

  connection_pooling:
    max_connections: 20
    connection_timeout_seconds: 30
    idle_timeout_minutes: 5

  resource_limits:
    max_memory_mb: 1024
    max_cpu_percent: 80
    max_disk_io_mb_per_second: 50

# Error Handling and Recovery
error_handling:
  retry_failed_operations: true
  max_retry_attempts: 3
  retry_backoff_seconds: [1, 5, 15]
  
  fallback_strategies:
    workflow_orchestrator_down: "queue_operations"
    notification_system_down: "email_fallback"
    git_repository_locked: "wait_and_retry"
    database_connection_lost: "local_cache"

  circuit_breaker:
    enabled: true
    failure_threshold: 5
    recovery_timeout_seconds: 60
    half_open_retry_count: 3

# Monitoring and Metrics
monitoring:
  enabled: true
  metrics_collection_interval_seconds: 60
  health_check_interval_seconds: 30
  
  tracked_metrics:
    - "active_workflows"
    - "workflow_completion_rate"
    - "average_review_time"
    - "reviewer_workload"
    - "notification_delivery_rate"
    - "quality_gate_pass_rate"
    - "branch_merge_rate"
    - "error_rate"

  alerts:
    - metric: "error_rate"
      threshold: 0.1
      duration_minutes: 5
      severity: "critical"
    
    - metric: "workflow_completion_rate"
      threshold: 0.8
      operator: "below"
      duration_minutes: 30
      severity: "warning"
    
    - metric: "average_review_time"
      threshold: 48
      unit: "hours"
      duration_minutes: 60
      severity: "warning"

# Security Settings
security:
  authentication_required: true
  role_based_access_control: true
  audit_all_operations: true
  encrypt_sensitive_data: true
  
  permissions:
    create_workflow: ["author", "content_manager", "administrator"]
    approve_content: ["content_approver", "administrator"]
    bypass_quality_gates: ["administrator"]
    access_all_workflows: ["content_manager", "administrator"]
    delete_workflows: ["administrator"]
    
  api_security:
    require_api_keys: true
    rate_limiting: true
    request_signing: false
    ip_whitelisting: false

# Data Retention and Cleanup
data_retention:
  workflow_data_retention_days: 365
  notification_history_retention_days: 90
  branch_metadata_retention_days: 180
  migration_history_retention_days: 730
  
  cleanup_schedule:
    enabled: true
    run_time: "02:00"  # 2 AM
    frequency: "daily"
    
  archived_data:
    compress_old_data: true
    archive_location: "archives/"
    archive_after_days: 90

# Integration Testing
testing:
  enable_test_mode: false
  test_data_directory: "test_data/"
  mock_external_services: false
  
  test_scenarios:
    - "simple_workflow_creation"
    - "multi_stage_review_process"
    - "escalation_handling"
    - "batch_migration"
    - "notification_delivery"
    - "quality_gate_enforcement"

# Backup and Disaster Recovery
backup:
  enabled: true
  backup_schedule: "daily"
  backup_time: "01:00"
  backup_location: "backups/"
  retention_days: 30
  
  backup_components:
    - "workflow_data"
    - "branch_metadata"
    - "notification_history"
    - "migration_history"
    - "configuration_files"
  
  disaster_recovery:
    automated_failover: false
    backup_repository_url: null
    recovery_procedures_documented: true

# External Integrations
external_integrations:
  jira:
    enabled: false
    create_tickets_on_escalation: false
    sync_status_updates: false
    
  slack:
    enabled: false
    workspace_integration: false
    custom_workflows: false
    
  github:
    enabled: true
    create_issues_for_problems: true
    sync_branch_status: true
    webhook_notifications: true
    
  confluence:
    enabled: false
    publish_documentation: false
    sync_content_updates: false