#!/usr/bin/env python3
"""
Automation script: generate a top-level chapters/INDEX.md from all chapter READMEs.

Walks each chapter directory in order, extracts the first H1 heading and a
one-paragraph description (first non-empty paragraph after the H1), and
builds a linked table of contents.

Usage:
    python generate_chapter_index.py [--output <path>]
"""

import argparse
import logging
import re
import sys
from pathlib import Path

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
)
log = logging.getLogger(__name__)

REPO_ROOT = Path(__file__).resolve().parents[2]
CHAPTERS_DIR = REPO_ROOT / "chapters"
DEFAULT_OUTPUT = CHAPTERS_DIR / "INDEX.md"

H1_RE = re.compile(r"^#\s+(.+)$", re.MULTILINE)
FRONTMATTER_RE = re.compile(r"^---\s*\n.*?\n---\s*\n", re.DOTALL)


def extract_description(text: str) -> str:
    """Return first substantive paragraph after the H1 heading."""
    # Strip frontmatter if present
    text = FRONTMATTER_RE.sub("", text).strip()
    # Skip the H1 line
    lines = text.splitlines()
    past_h1 = False
    para_lines: list[str] = []
    for line in lines:
        if not past_h1:
            if line.startswith("# "):
                past_h1 = True
            continue
        stripped = line.strip()
        if stripped.startswith("#"):
            break
        if stripped:
            para_lines.append(stripped)
        elif para_lines:
            break  # blank line ends the paragraph
    return " ".join(para_lines)[:300] or "No description available."


def build_index(chapters: list[Path]) -> str:
    """Build the full INDEX.md content."""
    lines = [
        "# Data Science Learning Handbook — Chapter Index",
        "",
        "This file is auto-generated by `scripts/automation/generate_chapter_index.py`.",
        "Do not edit manually.",
        "",
        "| # | Chapter | Description |",
        "|---|---------|-------------|",
    ]
    for i, chapter in enumerate(chapters, start=1):
        readme = chapter / "README.md"
        if not readme.exists():
            log.warning("No README.md in %s — skipping", chapter.name)
            continue
        text = readme.read_text(encoding="utf-8")
        m = H1_RE.search(text)
        title = m.group(1).strip() if m else chapter.name
        desc = extract_description(text)
        rel_path = chapter.relative_to(CHAPTERS_DIR)
        lines.append(f"| {i} | [{title}]({rel_path}/README.md) | {desc} |")

    lines += ["", "---", "_Generated automatically. Run `make index` to refresh._", ""]
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate chapter index")
    parser.add_argument("--output", default=str(DEFAULT_OUTPUT), help="Output file path")
    args = parser.parse_args()

    if not CHAPTERS_DIR.exists():
        log.error("chapters/ directory not found: %s", CHAPTERS_DIR)
        sys.exit(1)

    chapters = sorted(
        d for d in CHAPTERS_DIR.iterdir() if d.is_dir() and not d.name.startswith(".")
    )
    log.info("Indexing %d chapters", len(chapters))

    content = build_index(chapters)
    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(content, encoding="utf-8")
    log.info("Index written to %s", output)


if __name__ == "__main__":
    main()
