#!/bin/bash
# Generates a simple compliance report summarising scan results and project metadata

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
REPORT_DIR="$PROJECT_ROOT/reports"
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
REPORT_FILE="$REPORT_DIR/compliance-report-$TIMESTAMP.md"

mkdir -p "$REPORT_DIR"

echo "Generating compliance report → $REPORT_FILE"

cat > "$REPORT_FILE" <<EOF
# Compliance Report

**Generated:** $(date)
**Repository:** $(git -C "$PROJECT_ROOT" remote get-url origin 2>/dev/null || echo "local")
**Branch:** $(git -C "$PROJECT_ROOT" rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")
**Commit:** $(git -C "$PROJECT_ROOT" rev-parse --short HEAD 2>/dev/null || echo "unknown")

---

## Summary

| Check | Status |
|-------|--------|
| flake8 (style/errors) | $(command -v flake8 &>/dev/null && echo "available" || echo "not installed") |
| bandit (security linting) | $(command -v bandit &>/dev/null && echo "available" || echo "not installed") |
| pytest (unit tests) | $(command -v pytest &>/dev/null && echo "available" || echo "not installed") |

---

## Python Files Scanned

\`\`\`
$(find "$PROJECT_ROOT" -name "*.py" \
    -not -path "*/.git/*" \
    -not -path "*/node_modules/*" \
    -not -path "*/__pycache__/*" \
    | sort | sed "s|$PROJECT_ROOT/||")
\`\`\`

---

## Notes

- This report is auto-generated by \`scripts/generate-compliance-report.sh\`.
- For a full security scan run \`scripts/security-compliance.sh\` first.
- Store historical reports in \`reports/\` (excluded from Docker images).

EOF

echo "Compliance report written to: $REPORT_FILE"
